                                                                const videoElement = document.getElementById('bg-video');
                                                                    const sourceSelect = document.getElementById('sourceSelect');
                                                                        const cameraSelect = document.getElementById('cameraSelect');
                                                                            const fileInput = document.getElementById('fileInput');

                                                                                // カメラからの動画取得のための準備
                                                                                    async function setupCamera() {
                                                                                          const cameras = await navigator.mediaDevices.enumerateDevices();
                                                                                                const videoDevices = cameras.filter(device => device.kind === 'videoinput');
                                                                                                      videoDevices.forEach((device, index) => {
                                                                                                              const option = document.createElement('option');
                                                                                                                      option.value = device.deviceId;
                                                                                                                              option.text = `カメラ ${index + 1}`;
                                                                                                                                      cameraSelect.appendChild(option);
                                                                                                                                            });
                                                                                                                                                }

                                                                                                                                                    // カメラからの動画を表示
                                                                                                                                                        async function startCamera() {
                                                                                                                                                              const constraints = {
                                                                                                                                                                      video: {
                                                                                                                                                                                deviceId: { exact: cameraSelect.value },
                                                                                                                                                                                          width: window.innerWidth,
                                                                                                                                                                                                    height: window.innerHeight
                                                                                                                                                                                                            }
                                                                                                                                                                                                                  };
                                                                                                                                                                                                                        const stream = await navigator.mediaDevices.getUserMedia(constraints);
                                                                                                                                                                                                                              videoElement.srcObject = stream;
                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                  // ファイル選択時の処理
                                                                                                                                                                                                                                  fileInput.addEventListener('change', () => {
                                                                                                                                                                                                                                    const file = fileInput.files[0];
                                                                                                                                                                                                                                      const url = URL.createObjectURL(file);
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                          // 動画の読み込み
                                                                                                                                                                                                                                            videoElement.src = url;

                                                                                                                                                                                                                                              // 動画の読み込みが完了したら処理を実行
                                                                                                                                                                                                                                                videoElement.onloadedmetadata = () => {
                                                                                                                                                                                                                                                    const videoWidth = videoElement.videoWidth;
                                                                                                                                                                                                                                                        const videoHeight = videoElement.videoHeight;
                                                                                                                                                                                                                                                            const windowWidth = window.innerWidth;
                                                                                                                                                                                                                                                                const windowHeight = window.innerHeight;

                                                                                                                                                                                                                                                                    // 動画の縦サイズがウィンドウの縦サイズよりも小さい場合
                                                                                                                                                                                                                                                                        if (videoHeight < windowHeight) {
                                                                                                                                                                                                                                                                              const aspectRatio = videoWidth / videoHeight;
                                                                                                                                                                                                                                                                                    const targetWidth = windowHeight * aspectRatio;

                                                                                                                                                                                                                                                                                          // 動画を上下中央で横いっぱいに配置
                                                                                                                                                                                                                                                                                                videoElement.style.position = 'absolute';
                                                                                                                                                                                                                                                                                                      videoElement.style.top = `${(windowHeight - videoHeight) / 2}px`;
                                                                                                                                                                                                                                                                                                            videoElement.style.left = `${(windowWidth - targetWidth) / 2}px`;
                                                                                                                                                                                                                                                                                                                  videoElement.style.width = `${targetWidth}px`;
                                                                                                                                                                                                                                                                                                                        videoElement.style.height = `${windowHeight}px`;
                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                  // 動画を画面左上に配置
                                                                                                                                                                                                                                                                                                                                        videoElement.style.position = 'absolute';
                                                                                                                                                                                                                                                                                                                                              videoElement.style.top = '0px';
                                                                                                                                                                                                                                                                                                                                                    videoElement.style.left = '0px';
                                                                                                                                                                                                                                                                                                                                                          videoElement.style.width = '100%';
                                                                                                                                                                                                                                                                                                                                                                videoElement.style.height = '100%';
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                      };
                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                    // ソースの選択に応じて処理を切り替え
                                                                                                                                                                                                                                                                        sourceSelect.addEventListener('change', () => {
                                                                                                                                                                                                                                                                              if (sourceSelect.value === 'none') {
                                                                                                                                                                                                                                                                                      videoElement.srcObject = null;
                                                                                                                                                                                                                                                                                              videoElement.style.display = 'none';
                                                                                                                                                                                                                                                                                                    } else if (sourceSelect.value === 'file') {
                                                                                                                                                                                                                                                                                                            fileInput.style.display = 'block';
                                                                                                                                                                                                                                                                                                                    cameraSelect.style.display = 'none';
                                                                                                                                                                                                                                                                                                                            videoElement.style.display = 'block';
                                                                                                                                                                                                                                                                                                                                    videoElement.srcObject = null;
                                                                                                                                                                                                                                                                                                                                          } else {
                                                                                                                                                                                                                                                                                                                                                  fileInput.style.display = 'none';
                                                                                                                                                                                                                                                                                                                                                          cameraSelect.style.display = 'block';
                                                                                                                                                                                                                                                                                                                                                                  videoElement.style.display = 'block';
                                                                                                                                                                                                                                                                                                                                                                          setupCamera();
                                                                                                                                                                                                                                                                                                                                                                                  startCamera();
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                            });

                                                                                                                                                                                                                                                                                                                                                                                                // カメラ選択に応じて処理を切り替え
                                                                                                                                                                                                                                                                                                                                                                                                    cameraSelect.addEventListener('change', () => {
                                                                                                                                                                                                                                                                                                                                                                                                          startCamera();
                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                    // 最初は動画を使用しない選択肢をデフォルトとする
                                                                                                                                                                                                                                                                                                                                                                                                                                        sourceSelect.value = 'none';
                                                                                                                                                                                                                                                                                                                                                                                                                                            videoElement.style.display = 'none';

                                                                                                                                                                                                                                                                                                                                                                                                                                            const videoSetting = document.getElementById('v-set');
                                                                                                                                                                                                                                                                                                                                                                                                                                            const videoStatement = document.getElementById('video-statement');

                                                                                                                                                                                                                                                                                                                                                                                                                                            videoSetting.addEventListener('chage', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                videoElement.muted = videoSetting.value;
                                                                                                                                                                                                                                                                                                                                                                                                                                                videoStatement.innerHTML = "state:(" + videoSetting.value + ")";
                                                                                                                                                                                                                                                                                                                                                                                                                                            });